import { IWSResult } from '../../../../../xcore/WSQuery';
export declare class DevsGroupStorage {
    search: any;
    open_modal: boolean;
    middle_form: any;
    org_id: number;
    set_org_id: number;
    name: string;
    key_org: any;
    key_devsgr: any;
    latitude: string;
    longitude: string;
    info: string;
    parent_id: string;
    parent: string;
    select_parent_id: string;
    name_err: boolean;
    name_err_mess: string;
    org_err: boolean;
    org_err_mess: string;
    latitude_err: boolean;
    latitude_err_mess: string;
    longitude_err: boolean;
    longitude_err_mess: string;
    open_menu: boolean;
    defaultExpanded_devs_froups: Array<string>;
    checkbox_editing: boolean;
    open_modal_change: boolean;
    open_modal_move: boolean;
    devs_groups: Array<string>;
    constructor();
    setSearch(val: any): void;
    getSearch(): any;
    setOpenModalChDevsGr(val: boolean): void;
    getOpenModalChDevsGr(): boolean;
    setOpenModalMoveDevsGr(val: boolean): void;
    getOpenModalMoveDevsGr(): boolean;
    setCheckboxEd(val: boolean): void;
    getCheckboxEd(): boolean;
    setOpen_menu(val: boolean): void;
    getOpen_menu(): boolean;
    setOrgId(val: number): void;
    getOrgId(): number;
    setOrg(val: number): void;
    getOrg(): number;
    setKeyOrg(val: any): void;
    getKeyOrg(): any;
    setKeyDevsgr(val: any): void;
    getKeyDevsgr(): any;
    setOpenModal(val: boolean): void;
    getOpenModal(): boolean;
    setMiddleForm(val: any): void;
    getMiddleForm(): any;
    setInfo(val: any): void;
    getInfo(): any;
    setName(val: string): void;
    getName(): string;
    setLatitude(val: string): void;
    getLatitude(): string;
    setLongitude(val: string): void;
    getLongitude(): string;
    setParentId(val: string): void;
    getParentId(): string;
    setParent(val: string): void;
    getParent(): string;
    setSelectedParentId(val: string): void;
    getSelectedParentId(): string;
    setDevsGroups(val: Array<string>): void;
    getDevsGroups(): Array<string>;
    setDefaultExpandedDevsGroups(val: Array<string>): void;
    getDefaultExpandedDevsGroups(): Array<string>;
    setNameError(val: boolean): void;
    getNameError(): boolean;
    setNameError_mess(val: string): void;
    getNamaError_mess(): string;
    setLatitudeError(val: boolean): void;
    getLatitudeError(): boolean;
    setLatitudeError_mess(val: string): void;
    getLatitudeError_mess(): string;
    setLongitudeError(val: boolean): void;
    getLongitudeError(): boolean;
    setLongitudeError_mess(val: string): void;
    getLongitudeError_mess(): string;
    setOrgError(val: boolean): void;
    getOrgError(): boolean;
    set_NewDevGroup(name: string, value: any, _options?: any): Promise<void>;
    get_DevsGroups(name: string, value: any, _options?: any): Promise<void>;
    setDevsGroupsAll(dt: IWSResult): void;
    set_ChangeDevsGroups(name: string, value: any, _options?: any): Promise<void>;
}
