import { IWSResult } from '../../../../xcore/WSQuery';
export declare class ModalStorage {
    PersonalAccaunt: boolean;
    alert_message: string;
    act_mail_message: boolean;
    spawn_alert: boolean;
    family: string;
    name: string;
    father: string;
    telephone: string;
    login: string;
    old_password: string;
    new_password: string;
    repeat_password: string;
    email: string;
    info: string;
    act_mail: boolean;
    error_pass: boolean;
    error_message: string;
    errr_old_pass: boolean;
    error_old_message: string;
    errr_new_pass: boolean;
    error_new_message: string;
    modal: number;
    alert_dialog: boolean;
    cmd_error_pass: string;
    cmd_error_data: string;
    checked_email: boolean;
    email_err: boolean;
    email_err_mess: string;
    phone_err: boolean;
    phone_err_mess: string;
    modal_title: string;
    code: any;
    dt: any;
    error: boolean;
    error_mass: string;
    constructor();
    setSpawnAlert(val: boolean): void;
    getSpawnAlert(): boolean;
    setChecked(val: boolean): void;
    getChecked(): boolean;
    setCmdErrPass(val: string): void;
    getCmdErrPass(): string;
    setCmdErrData(val: string): void;
    getCmdErrData(): string;
    setPersonalAccaunt(val: boolean): void;
    getPersonalAccaunt(): boolean;
    setModal(val: number): void;
    getModal(): number;
    setAlertDialog(val: boolean): void;
    getAlertDialog(): boolean;
    setModalTitle(val: string): void;
    getModalTitle(): string;
    setError_emain(val: boolean): void;
    getError_emain(): boolean;
    set_emain(val: boolean): void;
    get_emain(): boolean;
    setEmail_message(val: string): void;
    getEmail_message(): string;
    setError_phone(val: boolean): void;
    getError_phone(): boolean;
    setPhone_message(val: string): void;
    getPhone_message(): string;
    setLogin(val: string): void;
    getLogin(): string;
    setError_pass(val: boolean): void;
    getError_pass(): boolean;
    setError_message(val: string): void;
    getError_message(): string;
    setErrr_old_pass(val: boolean): void;
    getErrr_old_pass(): boolean;
    setError_old_message(val: string): void;
    getError_old_message(): string;
    setErrr_new_pass(val: boolean): void;
    getErrr_new_pass(): boolean;
    setError_new_message(val: string): void;
    getError_new_message(): string;
    setFamily(val: string): void;
    getFamily(): string;
    setName(val: string): void;
    getName(): string;
    setFather(val: string): void;
    getFather(): string;
    setTelephone(val: string): void;
    getTelephone(): string;
    setOld_Pass(val: string): void;
    getOld_Pass(): string;
    setNew_Pass(val: string): void;
    getNew_Pass(): string;
    setRepeat_password(val: string): void;
    getRepeat_password(): string;
    setEmail(val: string): void;
    getEmail(): string;
    setInfo(val: string): void;
    getInfo(): string;
    setActMail(val: boolean): void;
    getActMail(): boolean;
    setCode(u: any): void;
    getCode(): any;
    setError(u: boolean): void;
    getError(): boolean;
    setErrorMass(u: string): void;
    getErorMass(): string;
    set_ActMail(name: string, value: any, _options?: any): Promise<void>;
    set_CUserData(name: string, value: any, _options?: any): Promise<void>;
    set_ChangePass(name: string, value: any, _options?: any): Promise<void>;
    onGetChangePass(dt: IWSResult): void;
    onGetCUserData(dt: IWSResult): void;
}
