import { IWSResult } from "../../../../xcore/WSQuery";
export declare class ModalLeftPanel {
    table_user: boolean;
    modal_registration_user: boolean;
    take_data: any;
    modal_tittle: string;
    result_save: string;
    organization: Array<string>;
    jobs_titles: Array<string>;
    users: Array<string>;
    jobs_titles_error: string;
    key_org: any;
    key_jobs: any;
    checkbox_editing: boolean;
    checkbox_reading: boolean;
    family: string;
    name: string;
    father: string;
    email: string;
    telephone: string;
    login: string;
    password: string;
    repeat_password: string;
    info: string;
    error_family: boolean;
    texthelp_family: string;
    error_name: boolean;
    texthelp_name: string;
    error_father: boolean;
    texthelp_father: string;
    error_email: boolean;
    texthelp_email: string;
    error_telephone: boolean;
    texthelp_telephone: string;
    error_login: boolean;
    texthelp_login: string;
    error_login_double: boolean;
    texthelp_login_double: string;
    error_password: boolean;
    texthelp_password: string;
    error_repeat_password: boolean;
    texthelp_repeat_password: string;
    full_name_org: string;
    name_org: string;
    inn: string;
    address: string;
    latitude: string;
    longitude: string;
    info_org: string;
    error_org: boolean;
    texthelp_org: string;
    error_jobs: boolean;
    texthelp_jobs: string;
    jobs_titles_new: string;
    error_full_name: boolean;
    texthelp_full_name: string;
    error_name_org: boolean;
    texthelp_name_org: string;
    error_inn: boolean;
    texthelp_inn: string;
    error_address: boolean;
    texthelp_address: string;
    error_full_name_double: boolean;
    texthelp_full_name_double: string;
    error_name_double: boolean;
    texthelp_name_double: string;
    error_inn_double: boolean;
    texthelp_inn_double: string;
    nodeid_user: string;
    nodeid_org: string;
    nodeid_jobstitles: string;
    constructor();
    setNodeidUser(val: string): void;
    getNodeidUser(): string;
    setNodeidOrg(val: string): void;
    getNodeidOrg(): string;
    setNodeidJobsTitles(val: string): void;
    getNodeidJobsTitles(): string;
    setOpenTableUsers(val: boolean): void;
    getOpenTableUsers(): boolean;
    setCheckboxEd(val: boolean): void;
    getCheckboxEd(): boolean;
    setCheckboxRead(val: boolean): void;
    getCheckboxRead(): boolean;
    setKeyOrg(val: any): void;
    getKeyOrg(): any;
    setKeyJobs(val: any): void;
    getKeyJobs(): any;
    setOrgAll(val: Array<string>): void;
    getOrgAll(): Array<string>;
    setJobsAll(val: Array<string>): void;
    getJobsAll(): Array<string>;
    setJobsAllError(val: string): void;
    getJobsAllError(): string;
    setAllUsers(val: Array<string>): void;
    getAllUsers(): Array<string>;
    setModalRegUser(val: boolean): void;
    getModalRegUser(): boolean;
    setTakeModal(val: any): void;
    getTakeModal(): any;
    setTittleModal(val: string): void;
    getTittleModal(): string;
    setFamily(val: string): void;
    getFamily(): string;
    setName(val: string): void;
    getName(): string;
    setFather(val: string): void;
    getFather(): string;
    setEmail(val: string): void;
    getEmail(): string;
    setTelephone(val: string): void;
    getTelephone(): string;
    setLogin(val: string): void;
    getLogin(): string;
    setPassword(val: string): void;
    getPassword(): string;
    setRepeatPassword(val: string): void;
    getRepeatPassword(): string;
    setInfo(val: string): void;
    getInfo(): string;
    setErrorFamily(val: boolean): void;
    getErrorFamily(): boolean;
    setTextHelpFamily(val: string): void;
    getTextHelpFamily(): string;
    setErrorName(val: boolean): void;
    getErrorName(): boolean;
    setTextHelpName(val: string): void;
    getTextHelpName(): string;
    setErrorFather(val: boolean): void;
    getErrorFather(): boolean;
    setTextHelpFather(val: string): void;
    getTextHelpFather(): string;
    setErrorEmail(val: boolean): void;
    getErrorEmail(): boolean;
    setTextHelpEmail(val: string): void;
    getTextHelpEmail(): string;
    setErrorTelephone(val: boolean): void;
    getErrorTelephone(): boolean;
    setTextHelpTelephone(val: string): void;
    getTextHelpTelephone(): string;
    setErrorLogin(val: boolean): void;
    getErrorLogin(): boolean;
    setTextHelpLogin(val: string): void;
    getTextHelpLogin(): string;
    setErrorLoginDouble(val: boolean): void;
    getErrorLoginDouble(): boolean;
    setTextHelpLoginDouble(val: string): void;
    getTextHelpLoginDouble(): string;
    setErrorPassword(val: boolean): void;
    getErrorPassword(): boolean;
    setTextHelpPassword(val: string): void;
    getTextHelpPassword(): string;
    setErrorRepeatPassword(val: boolean): void;
    getErrorRepeatPassword(): boolean;
    setTextHelpRepeatPassword(val: string): void;
    getTextHelpRepeatPassword(): string;
    setFullNameOrg(val: string): void;
    getFullNameOrg(): string;
    setNameOrg(val: string): void;
    getNameOrg(): string;
    setInn(val: string): void;
    getInn(): string;
    setAddress(val: string): void;
    getAddress(): string;
    setLatitude(val: string): void;
    getLatitude(): string;
    setLongitude(val: string): void;
    getLongitude(): string;
    setInfOrg(val: string): void;
    getInfOrg(): string;
    setErrorFullName(val: boolean): void;
    getErrorFullName(): boolean;
    setTextHelpFullName(val: string): void;
    getTextHelpFullName(): string;
    setErrorFullNameDouble(val: boolean): void;
    getErrorFullNameDouble(): boolean;
    setTextHelpFullNameDouble(val: string): void;
    getTextHelpFullNameDouble(): string;
    setErrorNameOrg(val: boolean): void;
    getErrorNameOrg(): boolean;
    setTextHelpNameOrg(val: string): void;
    getTextHelpNameOrg(): string;
    setErrorNameDouble(val: boolean): void;
    getErrorNameDouble(): boolean;
    setTextHelpNameDouble(val: string): void;
    getTextHelpNameDouble(): string;
    setErrorInn(val: boolean): void;
    getErrorInn(): boolean;
    setTextHelpInn(val: string): void;
    getTextHelpInn(): string;
    setErrorInnDouble(val: boolean): void;
    getErrorInnDouble(): boolean;
    setTextHelpInnDouble(val: string): void;
    getTextHelpInnDouble(): string;
    setErrorAddress(val: boolean): void;
    getErrorAddress(): boolean;
    setTextHelpAddress(val: string): void;
    getTextHelpAddress(): string;
    setNewJobsTitles(val: string): void;
    getNewJobsTitles(): string;
    setResulSave(val: string): void;
    getResulSave(): string;
    setErrorOrg(val: boolean): void;
    getErrorOrg(): boolean;
    setTextHelpOrg(val: string): void;
    getTextHelpOrg(): string;
    setErrorJobs(val: boolean): void;
    getErrorJobs(): boolean;
    setTextHelpJobs(val: string): void;
    getTextHelpJobs(): string;
    get_AllUsers(name: string, value: any, _options?: any): Promise<void>;
    setUsersAll(dt: IWSResult): void;
    get_Org(name: string, value: any, _options?: any): Promise<void>;
    setAllOrganization(dt: IWSResult): void;
    get_Jobs(name: string, value: any, _options?: any): Promise<void>;
    setAllJobsTitle(dt: IWSResult): void;
    set_NewUser(name: string, value: any, _options?: any): Promise<void>;
    set_NewOrg(name: string, value: any, _options?: any): Promise<void>;
    set_NewJobTitle(name: string, value: any, _options?: any): Promise<void>;
}
