import * as React from 'react';
import { SvgIconProps } from '@mui/material/SvgIcon';
import { TreeItemProps } from '@mui/lab/TreeItem';
import { TransitionProps } from '@mui/material/transitions';
export declare function MinusSquare(props: SvgIconProps): JSX.Element;
export declare function PlusSquare(props: SvgIconProps): JSX.Element;
export declare function CloseSquare(props: SvgIconProps): JSX.Element;
export declare function TransitionComponent(props: TransitionProps): JSX.Element;
export declare const StyledMua: import("@emotion/styled").StyledComponent<TreeItemProps & import("@mui/system").MUIStyledCommonProps<import("@mui/material").Theme>, {}, {}>;
export declare const id_dev_sess: (event: any, node: any) => Promise<void>;
export declare const handleChange: (event: any, node: any) => Promise<void>;
export declare const options: (event: any, node: any) => Promise<void>;
export declare const customizedGroupTick: (props: any) => JSX.Element;
export declare const handleChangePage: (event: React.MouseEvent<HTMLButtonElement> | null, newPage: number) => void;
export declare const handleChangeRowsPerPage: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
